---
- name: Update and upgrade apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Set timezone	
  become: yes	
  command: timedatectl set-timezone {{ timezone }}
  when: "{{ system }} != 'wsl'"

- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  