---
- name: Update and upgrade apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  