---
- name: Configure git
  command: git config --global {{ item.0 }} {{ item.1 }}
  with_together:
    - [user.name, user.email]
    - ["{{ git_name}}", "{{ git_email }}"]

- name: Download config files
  get_url:
    url: "{{ item }}"
    dest: ~/
  loop: "{{ github_dotfiles }}"

- name: Set vim as default editor
  become: yes
  command: update-alternatives --set editor /usr/bin/vim.basic

- name: Install vim plugins from .vimrc
  command: vim +'PlugInstall --sync' +qa
  args:
    stdin: "\n"

- name: Get username
  become: no
  local_action: command whoami
  register: username_result

- name: Set zsh as default shell
  become: yes
  user:
    name: "{{ username_result.stdout }}"
    shell: /usr/bin/zsh
