---
- name: Provision Ubuntu dev environment
  hosts: localhost
  connection: local
  tasks:
  - name: Basic provisioning
    include_role:
      name: "{{ item }}"
    loop:
      - system
      - ssh
      - plugins
      - configure
  
  - name: Provision with Docker
    include_role:
      name: docker
    when: "system != 'wsl'"
