---
- name: Provision Ubuntu dev environment
  hosts: all
  connection: local
  tasks:
  - name: Basic provisioning
    include_role:
      name: "{{ outer_item }}"
    loop:
      - system
      - internet
      - plugins
      - configure
      - python
      - node
    loop_control:
      loop_var: outer_item
  
  - name: Provision with Docker
    include_role:
      name: docker
    when: "system == 'full'"
