---
- name: Ensure Docker dependencies are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ dependencies }}"

- name: Add Docker GPG key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Get current distribution version
  become: yes
  command: lsb_release -sc
  register: distro_version

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ distro_version.stdout }} stable"
    state: present
  
- name: Install Docker engine
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ packages }}"

- name: Ensure Docker group exists
  group:
    name: docker
    state: present

- name: Add user to Docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes

- name: Get Docker-Compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: a+x
