---
- name: Check if SSH files exist
  stat:
    path: ~/.ssh/id_rsa
  register: ssh_result

- name: Generate ssh files
  command: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
  when: not ssh_result.stat.exists

- name: Enable and start Network Manager
  systemd:
    name: NetworkManager.service
    state: started
    enabled: yes
  when: "(system == 'full') or (system == 'vm')"

- name: Set UFW to allow SSH
  become: yes
  command: ufw limit ssh
  when: "(system == 'full') or (system == 'vm')"

- name: Enable UFW
  become: yes
  command: ufw enable
  when: "(system == 'full') or (system == 'vm')"
