---
timezone: "America/New_York"
packages:
  - vim
  - git
  - zsh
  - tmux
  - python3
  - python3-venv
  - python3-pip
  - openjdk-11-jdk
  - zip
  - unzip
full_packages:
  - network-manager
  - ufw
